#!/usr/bin/env python3
"""Fuzz AuroraCore's version ordering against real dpkg.

dpkg is the oracle: every pair is resolved by `dpkg --compare-versions`, and the
Python mirror of the Swift algorithm must agree. Pairs where they disagree are
printed, and the full agreed table is written out as a test fixture so CI checks
the *Swift* transcription against dpkg-derived truth as well.

The committed table was generated against dpkg 1.22.11; CI re-derives it with
whatever dpkg it has installed, which is why the check is "the mirror agrees with
this dpkg" rather than "the file is unchanged".
"""
import itertools
import os
import random
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import version_mirror as vm

DPKG = "dpkg"


def dpkg_compare(a, b):
    """Return -1/0/1 per dpkg, or None when dpkg rejects the version string."""
    for op, want in (("lt", -1), ("eq", 0), ("gt", 1)):
        r = subprocess.run(
            [DPKG, "--compare-versions", a, op, b], capture_output=True
        )
        if r.returncode == 0:
            return want
        if r.returncode not in (0, 1):
            return None
    return None


ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.+-~:"


def random_version(rng):
    n = rng.randint(1, 10)
    body = "".join(rng.choice(ALPHABET) for _ in range(n))
    if rng.random() < 0.7:  # most versions start with a digit
        body = rng.choice("0123456789") + body
    return body


EDGE = [
    "0", "1", "1.0", "1.0-1", "1.0-2", "1.00-1", "1:1.0", "0:1.0", "1.0~rc1",
    "1.0~~", "1.0~", "1.0-1~bpo1", "2.0", "10.0", "1.0a", "1.0.1-1ubuntu2",
    "1.0-1.0", "1.0+dfsg1-1", "1.0.dfsg-1", "1.0a-1", "1.0-alpha-1",
    "1:0", "1:1", "2:1", "1.0-0", "0.0", "0.9.9.9", "1.0.0.0",
    "1.0-1ubuntu1~22.04.1", "17.0.0+20230910120000~d3f4a5b", "1.0.0~beta1",
    "1.0.0.beta1", "1.0.0beta1", "5.6.12-1+deb12u1", "1.0+really0.9-1",
    "1.0-rc1", "1.0.RC1", "1.0_rc1", "1.0~rc1~git20200101", "1.0-1-1",
]


def main():
    rng = random.Random(20260930)
    versions = list(EDGE)
    seen = set(versions)
    while len(versions) < 140:
        v = random_version(rng)
        if v and v not in seen and "-" not in v[:0]:
            seen.add(v)
            versions.append(v)

    mismatches = []
    checked = 0
    rows = []
    # every edge pair plus a random sample of the rest
    pairs = list(itertools.combinations(EDGE, 2))
    for v in versions:
        if v not in EDGE:
            for other in rng.sample(EDGE, min(6, len(EDGE))):
                pairs.append((v, other))
    for a, b in pairs:
        expected = dpkg_compare(a, b)
        if expected is None:
            print("dpkg rejected: %r %r" % (a, b))
            continue
        checked += 1
        got = vm.compare(a, b)
        sym = "<" if got < 0 else (">" if got > 0 else "==")
        rows.append("%s\t%s\t%s" % (a, sym, b))
        if got != expected:
            mismatches.append((a, b, expected, got))
            if len(mismatches) <= 20:
                print("MISMATCH a=%r b=%r dpkg=%d mirror=%d" % (a, b, expected, got))

    out = os.path.join(ROOT, "Tests", "AuroraCoreTests", "Fixtures", "version-vectors.tsv")
    with open(out, "w") as f:
        f.write("# generated by Tools/fuzz_version_order.py against dpkg 1.22.11\n")
        f.write("# left <relation> right, relation in {<, >, ==}\n")
        for row in sorted(set(rows)):
            f.write(row + "\n")

    print("checked %d pairs, %d mismatches, %d vectors written"
          % (checked, len(mismatches), len(set(rows))))
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
